export enum JSONTokenType {
    Root = 0,
    Object = 1,
    Array = 2,
    String = 3,
    Number = 4,
    True = 5,
    False = 6,
    Null = 7,
    Key = 8,
    Hex = 9,
    CodePoints = 10,
    Escape = 11,
    Whitespaces = 12,
    Comma = 13,
    Colon = 14,
    SingleLineComment = 15,
    MultiLineComment = 16,
};